spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo2
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate


demo:
  openapi:
    dev-url: http://localhost:8080

application:
  security:
    jwt:
      secret-key: hbkATduY3tl25vO85joJt5iqOFAlcjGh1NSdQBfpy1eVUxoeekejqWDPpLIV2H/c
      expiration: 86400000 #a day
      refresh-token:
        expiration: 604800000 #7 days