spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo2
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

bezkoder:
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://bezkoder-api.com